language: node_js
node_js:
  - '8'
  - '10'
  - '11'

notifications:
  email:
    on_success: never
    on_failure: always

script: yarn build

deploy:
  provider: npm
  email: npm@jupiterone.io
  api_key:
    secure: 'travis encrypt <npm@jupiterone.io API key from Dashlane>'
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: JupiterOne/graph-template
    node: '8'
